name: Erlang CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/emqx/emqx-builder/5.0-14:1.13.3-24.2.1-1-ubuntu20.04

    steps:
    - uses: actions/checkout@v3
    - name: Xref
      run: make xref
    - name: Make release
      run: make rel
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: emqx_log_action_plugin
        path: _build/default/emqx_plugrel/*.tar.gz
